# Very simple wallpaper config, change as you find fit for more monitors and etc

wallpaper {
    monitor =
    # symlink set by scripts/wallpaper.sh (SUPER + W)
    path = ~/.cache/current-wallpaper
    fit_mode = cover
}

