# petiole kitty theme
  # Basics
  background            #0f130d
  foreground            #ddd5bc
  cursor                #d78a51
  cursor_text_color     #0f130d
  selection_background  #333c29
  selection_foreground  #ddd5bc
  url_color             #d78a51
  active_border_color   #9cba8d
  inactive_border_color #333c29

  # Tabs
  active_tab_background   #9cba8d
  active_tab_foreground   #0f130d
  inactive_tab_background #171c13
  inactive_tab_foreground #6d7059
  tab_bar_background      #0f130d

               
  # black                          
  color0  #1f2518
  color8  #6d7059
  # red                
  color1  #c8765e
  color9  #dd8d74
  # green                               
  color2  #85a271
  color10 #9cba8d
  # yellow            
  color3  #c9b074
  color11 #ddc58a
  # blue        
  color4  #7f9fa8
  color12 #97b6bd
  # magenta             
  color5  #b98a9a
  color13 #cca0ae
  # cyan               
  color6  #83b0a0
  color14 #9cc6b5
  # white                        
  color7  #bdb8a2
  color15 #ddd5bc
